### ISSUE TITLE
result of culane when i detect my image is not good

### ISSUE THREAD

**Issue by ggyybb** [aliyun/conditional-lane-detection#18]
![0_2](https://user-images.githubusercontent.com/61568153/127123305-f4c4e309-bfd8-4b95-801a-8848c5f61c74.png)
I tried your method for detecting my own image,but result like this picture, it seems to be right, and may be post-progress is not right, i can't solve it, please help me!

**Comment by Gooddz1** [comment]
请问怎么检测自己的图片，求指导

**Comment by ggyybb** [comment]
> 请问怎么检测自己的图片，求指导

这样
https://github.com/aliyun/conditional-lane-detection/issues/8

**Comment by Wolfwjs** [comment]
请教大佬 是用的作者给出的配置环境吗
```
MMCV: 0.5.6
MMDetection: 2.0.0+73c2043
```
遇到了个问题是test的时候报error，
```
(openmm) [wangjinsheng@HOST-10-198-32-69 tools]$ sh test_slurm.sh 
[                                                  ] 0/2782, elapsed: 0s, ETA:[                                                  ] 0/2782, elapsed: 0s, ETA:Traceback (most recent call last):
Traceback (most recent call last):
  File "test.py", line 149, in <module>
  File "test.py", line 149, in <module>
    main()
  File "test.py", line 127, in main
    args.show_score_thr)
  File "/mnt/lustre/wangjinsheng/project/lane-detection/conditional-lane-detection/mmdet/apis/test.py", line 28, in single_gpu_test
    main()
  File "test.py", line 127, in main
    args.show_score_thr)
  File "/mnt/lustre/wangjinsheng/project/lane-detection/conditional-lane-detection/mmdet/apis/test.py", line 28, in single_gpu_test
    img_tensor = data['img'][0]
TypeError: 'DataContainer' object is not subscriptable
    img_tensor = data['img'][0]
TypeError: 'DataContainer' object is not subscriptable
```

**Comment by ggyybb** [comment]
> 请教大佬 是用的作者给出的配置环境吗
> 
> ```
> MMCV: 0.5.6
> MMDetection: 2.0.0+73c2043
> ```
> 
> 遇到了个问题是test的时候报error，
> 
> ```
> (openmm) [wangjinsheng@HOST-10-198-32-69 tools]$ sh test_slurm.sh 
> [                                                  ] 0/2782, elapsed: 0s, ETA:[                                                  ] 0/2782, elapsed: 0s, ETA:Traceback (most recent call last):
> Traceback (most recent call last):
>   File "test.py", line 149, in <module>
>   File "test.py", line 149, in <module>
>     main()
>   File "test.py", line 127, in main
>     args.show_score_thr)
>   File "/mnt/lustre/wangjinsheng/project/lane-detection/conditional-lane-detection/mmdet/apis/test.py", line 28, in single_gpu_test
>     main()
>   File "test.py", line 127, in main
>     args.show_score_thr)
>   File "/mnt/lustre/wangjinsheng/project/lane-detection/conditional-lane-detection/mmdet/apis/test.py", line 28, in single_gpu_test
>     img_tensor = data['img'][0]
> TypeError: 'DataContainer' object is not subscriptable
>     img_tensor = data['img'][0]
> TypeError: 'DataContainer' object is not subscriptable
> ```

对啊，作者 的环境，没遇到问题

**Comment by wywywy01** [comment]
你应该贴出来：你用的是基于哪个数据集和模型结构的结果，并且传上原始的图片。这样别人才能帮你看呀
You should post it: which data set and model structure are you based on, and send the original picture. So that others can watch it for you

**Comment by Wolfwjs** [comment]
谢谢各位，上面那个问题已经解决了~

**Comment by byeciao** [comment]
> 谢谢各位，上面那个问题已经解决了~

你好，请问是怎么解决的呢
