### ISSUE TITLE
TypeError: 'DataContainer' object is not subscriptable

### ISSUE THREAD

**Issue by Wolfwjs** [aliyun/conditional-lane-detection#21]
请教大佬 ，用推荐的环境配置
```
MMCV: 0.5.6
MMDetection: 2.0.0+73c2043
```
train的时候没问题，但是test的时候报如下error，检查了数据集是没问题的，还可能是哪里的问题呢
```
(openmm) [wangjinsheng@HOST-10-198-32-69 tools]$ sh test_slurm.sh 
[                                                  ] 0/2782, elapsed: 0s, ETA:[                                                  ] 0/2782, elapsed: 0s, ETA:Traceback (most recent call last):
Traceback (most recent call last):
  File "test.py", line 149, in <module>
  File "test.py", line 149, in <module>
    main()
  File "test.py", line 127, in main
    args.show_score_thr)
  File "/mnt/lustre/wangjinsheng/project/lane-detection/conditional-lane-detection/mmdet/apis/test.py", line 28, in single_gpu_test
    main()
  File "test.py", line 127, in main
    args.show_score_thr)
  File "/mnt/lustre/wangjinsheng/project/lane-detection/conditional-lane-detection/mmdet/apis/test.py", line 28, in single_gpu_test
    img_tensor = data['img'][0]
TypeError: 'DataContainer' object is not subscriptable
    img_tensor = data['img'][0]
TypeError: 'DataContainer' object is not subscriptable
```

**Comment by inSight-mk1** [comment]
怎么解决的啊？
