### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by wangnian97** [aliyun/conditional-lane-detection#34]
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 154, in main
    meta=meta)
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.0.0+c57b242-py3.7-linux-x86_64.egg/mmdet/apis/train.py", line 165, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 226, in __iter__
    for idx in self.sampler:
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.0.0+c57b242-py3.7-linux-x86_64.egg/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

我用的 python tools/train.py configs/condlanenet/culane/culane_small_train.py在服务器训练，想请教下这个错误出现的原因

**Comment by qiuqc1** [comment]
数据集data_root设置有问题
