### ISSUE TITLE
There is one case where the lane start point deviates from the lane.

### ISSUE THREAD

**Issue by feifeiwei** [aliyun/conditional-lane-detection#42]
Therefore, a polygonal line will appear at the starting point of the lane.

**Comment by wangshuangbin** [comment]
hello Feifei
         
           there was an issue when i run test_culane.py, i used the command 
          python demo/ configs/condlanenet/culane/culane_small_test.py weight/culane_small.pth
          and here is the description the error
         Traceback (most recent call last):

  File "demo/webcam_demo.py", line 54, in <module>
    main()
  File "demo/webcam_demo.py", line 36, in main
    result = inference_detector(model, img)
  File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/apis/inference.py", line 82, in inference_detector
    data = test_pipeline(data)
  File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/datasets/pipelines/compose.py", line 29, in __call__
    data = t(data)
  File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/datasets/pipelines/lane_formating.py", line 421, in __call__
    valid = self.target(results)
  File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/datasets/pipelines/lane_formating.py", line 333, in target
    gt_points = results['gt_points']
KeyError: 'gt_points'

do you have any ideas? wait for your feedback, this is very important for me, thank you !!

**Comment by batuhanbeytekin** [comment]
> hello Feifei
> 
> ```
>        there was an issue when i run test_culane.py, i used the command 
>       python demo/ configs/condlanenet/culane/culane_small_test.py weight/culane_small.pth
>       and here is the description the error
>      Traceback (most recent call last):
> ```
> 
> File "demo/webcam_demo.py", line 54, in main() File "demo/webcam_demo.py", line 36, in main result = inference_detector(model, img) File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/apis/inference.py", line 82, in inference_detector data = test_pipeline(data) File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/datasets/pipelines/compose.py", line 29, in **call** data = t(data) File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/datasets/pipelines/lane_formating.py", line 421, in **call** valid = self.target(results) File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/datasets/pipelines/lane_formating.py", line 333, in target gt_points = results['gt_points'] KeyError: 'gt_points'
> 
> do you have any ideas? wait for your feedback, this is very important for me, thank you !!

Did you solve this issue? I got the same problem when i run image_demo.py.

**Comment by 18811598673** [comment]
> About KeyError: 'gt_points'.
Have you solved the issue? I also got the same problem.

**Comment by 18811598673** [comment]
> > hello Feifei
> > ```
> >        there was an issue when i run test_culane.py, i used the command 
> >       python demo/ configs/condlanenet/culane/culane_small_test.py weight/culane_small.pth
> >       and here is the description the error
> >      Traceback (most recent call last):
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "demo/webcam_demo.py", line 54, in main() File "demo/webcam_demo.py", line 36, in main result = inference_detector(model, img) File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/apis/inference.py", line 82, in inference_detector data = test_pipeline(data) File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/datasets/pipelines/compose.py", line 29, in **call** data = t(data) File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/datasets/pipelines/lane_formating.py", line 421, in **call** valid = self.target(results) File "/home/didi/kerwin/conditional-lane-detection-master/mmdet/datasets/pipelines/lane_formating.py", line 333, in target gt_points = results['gt_points'] KeyError: 'gt_points'
> > do you have any ideas? wait for your feedback, this is very important for me, thank you !!
> 
> Did you solve this issue? I got the same problem when i run image_demo.py.

About KeyError: 'gt_points'.
Have you solved the issue? I also got the same problem.
