### ISSUE TITLE
怎么使用模型检测自己的数据（没有标注

### ISSUE THREAD

**Issue by GongDianCheng** [aliyun/conditional-lane-detection#54]
您好，感谢您的开源代码。最近在学习condlaneNet，请问怎么使用模型直接检测自己的样本呀，直接输出检测的结果

**Comment by jyang68sh** [comment]
新建一个自己的数据集对象继承 https://github.com/aliyun/conditional-lane-detection/blob/master/mmdet/datasets/custom.py 

可以参考 https://mmdetection.readthedocs.io/en/latest/2_new_data_model.html

**Comment by GongDianCheng** [comment]
@jyang68sh 感谢您的回答！

**Comment by GongDianCheng** [comment]
@jyang68sh 大佬您好，我看完您法的连接了，找到了一个demo，但是测试的时候，还是报错
`Traceback (most recent call last):
  File "/home/gdc/gong/lane-detection/conditional-lane-detection-master/test.py", line 7, in <module>
    result=inference_detector(model,img)
  File "/home/gdc/gong/lane-detection/conditional-lane-detection-master/mmdet/apis/inference.py", line 82, in inference_detector
    data = test_pipeline(data)
  File "/home/gdc/gong/lane-detection/conditional-lane-detection-master/mmdet/datasets/pipelines/compose.py", line 29, in __call__
    data = t(data)
  File "/home/gdc/gong/lane-detection/conditional-lane-detection-master/mmdet/datasets/pipelines/lane_formating.py", line 576, in __call__
    valid = self.target(results)
  File "/home/gdc/gong/lane-detection/conditional-lane-detection-master/mmdet/datasets/pipelines/lane_formating.py", line 477, in target
    gt_points = results['gt_points']
KeyError: 'gt_points'`
也就是说还是需要标签信息
请问您之前测试，这个问题怎么解决的

**Comment by jyang68sh** [comment]
config 文件， test里的ann_dir = ‘’
评测的时候不要加 --eval 选项
你看下代码，不要让他走评测metric那里

**Comment by GongDianCheng** [comment]
@jyang68sh 感谢您的恢复，我明白您的思路了，但是我查看configs下的curvelanes_small_test.py，您说的ann_dir没有选项，demo也没有加--eval
`from mmdet.apis import  init_detector,inference_detector
import  mmcv
config_file = 'configs/condlanenet/curvelanes/curvelanes_small_test.py'
checkpoint_file = 'curvelanes_small.pth'
model=init_detector(config_file,checkpoint_file,device='cuda:0')
img='dataset/test/bgr8_zacg_1650609899571658538.jpg'
result=inference_detector(model,img)
model.show_result(img, result)

`

**Comment by jyang68sh** [comment]
那你可能手动制止一下读取真值的方法，然后传回空的字典。看下代码吧

**Comment by GongDianCheng** [comment]
@jyang68sh 好的。再次感谢您的思路，我看一下代码执行过程
